export const FONTS = [
  {
    name: 'Geist',
    value: 'geist',
    cssVar: '--font-geist',
    fontFamily: '\'Geist\', sans-serif',
    type: 'sans',
  },
  {
    name: 'Inter',
    value: 'inter',
    cssVar: '--font-inter',
    fontFamily: '\'Inter\', sans-serif',
    type: 'sans',
  },
  {
    name: 'Noto Sans',
    value: 'noto-sans',
    cssVar: '--font-noto-sans',
    fontFamily: '\'Noto Sans\', sans-serif',
    type: 'sans',
  },
  {
    name: 'Nunito Sans',
    value: 'nunito-sans',
    cssVar: '--font-nunito-sans',
    fontFamily: '\'Nunito Sans\', sans-serif',
    type: 'sans',
  },
  {
    name: 'Figtree',
    value: 'figtree',
    cssVar: '--font-figtree',
    fontFamily: '\'Figtree\', sans-serif',
    type: 'sans',
  },
  {
    name: 'Roboto',
    value: 'roboto',
    cssVar: '--font-roboto',
    fontFamily: '\'Roboto\', sans-serif',
    type: 'sans',
  },
  {
    name: 'Raleway',
    value: 'raleway',
    cssVar: '--font-raleway',
    fontFamily: '\'Raleway\', sans-serif',
    type: 'sans',
  },
  {
    name: 'DM Sans',
    value: 'dm-sans',
    cssVar: '--font-dm-sans',
    fontFamily: '\'DM Sans\', sans-serif',
    type: 'sans',
  },
  {
    name: 'Public Sans',
    value: 'public-sans',
    cssVar: '--font-public-sans',
    fontFamily: '\'Public Sans\', sans-serif',
    type: 'sans',
  },
  {
    name: 'Outfit',
    value: 'outfit',
    cssVar: '--font-outfit',
    fontFamily: '\'Outfit\', sans-serif',
    type: 'sans',
  },
  {
    name: 'Oxanium',
    value: 'oxanium',
    cssVar: '--font-oxanium',
    fontFamily: '\'Oxanium\', sans-serif',
    type: 'sans',
  },
  {
    name: 'Manrope',
    value: 'manrope',
    cssVar: '--font-manrope',
    fontFamily: '\'Manrope\', sans-serif',
    type: 'sans',
  },
  {
    name: 'Space Grotesk',
    value: 'space-grotesk',
    cssVar: '--font-space-grotesk',
    fontFamily: '\'Space Grotesk\', sans-serif',
    type: 'sans',
  },
  {
    name: 'Montserrat',
    value: 'montserrat',
    cssVar: '--font-montserrat',
    fontFamily: '\'Montserrat\', sans-serif',
    type: 'sans',
  },
  {
    name: 'IBM Plex Sans',
    value: 'ibm-plex-sans',
    cssVar: '--font-ibm-plex-sans',
    fontFamily: '\'IBM Plex Sans\', sans-serif',
    type: 'sans',
  },
  {
    name: 'Source Sans 3',
    value: 'source-sans-3',
    cssVar: '--font-source-sans-3',
    fontFamily: '\'Source Sans 3\', sans-serif',
    type: 'sans',
  },
  {
    name: 'Instrument Sans',
    value: 'instrument-sans',
    cssVar: '--font-instrument-sans',
    fontFamily: '\'Instrument Sans\', sans-serif',
    type: 'sans',
  },
  {
    name: 'JetBrains Mono',
    value: 'jetbrains-mono',
    cssVar: '--font-jetbrains-mono',
    fontFamily: '\'JetBrains Mono\', monospace',
    type: 'mono',
  },
  {
    name: 'Geist Mono',
    value: 'geist-mono',
    cssVar: '--font-geist-mono',
    fontFamily: '\'Geist Mono\', monospace',
    type: 'mono',
  },
  {
    name: 'Noto Serif',
    value: 'noto-serif',
    cssVar: '--font-noto-serif',
    fontFamily: '\'Noto Serif\', serif',
    type: 'serif',
  },
  {
    name: 'Roboto Slab',
    value: 'roboto-slab',
    cssVar: '--font-roboto-slab',
    fontFamily: '\'Roboto Slab\', serif',
    type: 'serif',
  },
  {
    name: 'Merriweather',
    value: 'merriweather',
    cssVar: '--font-merriweather',
    fontFamily: '\'Merriweather\', serif',
    type: 'serif',
  },
  {
    name: 'Lora',
    value: 'lora',
    cssVar: '--font-lora',
    fontFamily: '\'Lora\', serif',
    type: 'serif',
  },
  {
    name: 'Playfair Display',
    value: 'playfair-display',
    cssVar: '--font-playfair-display',
    fontFamily: '\'Playfair Display\', serif',
    type: 'serif',
  },
] as const

export type Font = (typeof FONTS)[number]

export const FONT_HEADING_OPTIONS = [
  {
    name: 'Inherit',
    value: 'inherit',
    cssVar: '',
    fontFamily: 'inherit',
    type: 'default',
  },
  ...FONTS,
] as const

export type FontHeadingOption = (typeof FONT_HEADING_OPTIONS)[number]
