import type { RegistryBase, RegistryContentType } from './registry.config'
import { exec } from 'node:child_process'
import { existsSync, promises as fs } from 'node:fs'

import path, { resolve } from 'node:path'
import { rimraf } from 'rimraf'
import { getAllBlocks } from '@/lib/blocks'
import { registry } from '@/registry/index'
import { ui } from '~/registry/new-york-v4/ui/_registry'
import { crawlBlock, crawlChart, crawlComposables, crawlExample, crawlUI } from './crawl-content'
import { registryConfig } from './registry.config'

async function writeFile(path: string, payload: any) {
  return fs.writeFile(
    path,
    `${payload}\n`,
    'utf8',
  )
}

/**
 * Get the appropriate crawl function based on type
 */
function getCrawlFunction(crawlType: RegistryContentType['crawlType']) {
  const crawlFunctions = {
    ui: crawlUI,
    block: crawlBlock,
    chart: crawlChart,
    example: crawlExample,
    composable: crawlComposables,
  }
  return crawlFunctions[crawlType]
}

/**
 * Build a registry file for a specific content type within a base
 */
async function buildRegistryContentType(
  base: RegistryBase,
  contentType: RegistryContentType,
) {
  const crawlFunction = getCrawlFunction(contentType.crawlType)
  const sourcePath = resolve('registry', base.path, contentType.path)

  // Check if the source path exists
  if (!existsSync(sourcePath)) {
    console.warn(`⚠️  Skipping ${base.name}/${contentType.name} - path does not exist: ${sourcePath}`)
    return null
  }

  // eslint-disable-next-line no-console
  console.log(`📦 Building ${base.name}/${contentType.name}...`)

  const result = await crawlFunction(sourcePath)
  const outputPath = resolve('registry', contentType.outputFile)

  // Ensure output directory exists
  await fs.mkdir(path.dirname(outputPath), { recursive: true })

  await writeFile(
    outputPath,
    `import type { Registry } from "shadcn-vue/schema"

export const ${contentType.name}: Registry["items"] = ${JSON.stringify(result ?? '', null, 2)}`,
  )

  exec(`eslint --fix ${outputPath}`)

  return result
}

/**
 * Build all content types for a specific base
 */
async function buildBaseRegistry(base: RegistryBase) {
  // eslint-disable-next-line no-console
  console.log(`\n🎨 Processing base: ${base.name}`)

  const results: Record<string, any> = {}

  for (const contentType of base.contentTypes) {
    const result = await buildRegistryContentType(base, contentType)
    if (result) {
      results[contentType.name] = result
    }
  }

  return results
}

/**
 * Build registry index file (for main registry only)
 */
async function buildRegistryIndex() {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const Index: Record<string, any> = {`

  for (const item of registry.items) {
    const resolveFiles = item.files?.map(
      file => `registry/new-york-v4/${file.path}`,
    )
    if (!resolveFiles) {
      continue
    }

    const componentPath = item.files?.[0]?.path
      ? `@/registry/new-york-v4/${item.files[0].path}`
      : ''

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ''}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${item.files?.map((file) => {
      const filePath = `registry/new-york-v4/${typeof file === 'string' ? file : file.path}`
      const resolvedFilePath = path.resolve(filePath)
      return typeof file === 'string'
        ? `"${resolvedFilePath}"`
        : `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ''}"
    }`
    })}],
    categories: ${JSON.stringify(item.categories)},
    meta: ${JSON.stringify(item.meta)},
  },`
  }

  index += `
  }`

  // eslint-disable-next-line no-console
  console.log(`#️⃣  ${Object.keys(registry.items).length} items found`)

  // Write style index.
  rimraf.sync(path.join(process.cwd(), 'registry/__index__.ts'))
  await fs.writeFile(path.join(process.cwd(), 'registry/__index__.ts'), index)
}

/**
 * Build registry JSON file for a specific base
 */
async function buildRegistryJsonFile(base: RegistryBase) {
  if (!base.buildMainRegistry) {
    // eslint-disable-next-line no-console
    console.log(`⏭️  Skipping registry.json for ${base.name}`)
    return
  }

  // eslint-disable-next-line no-console
  console.log(`💅 Building registry.json for ${base.name}...`)

  // 1. Fix the path for registry items.
  const fixedRegistry = {
    ...registry,
    items: registry.items.map((item) => {
      const files = item.files?.map((file) => {
        return {
          ...file,
          path: `registry/${base.path}/${file.path}`,
        }
      })

      return {
        ...item,
        files,
      }
    }),
  }

  // 2. Create the output directory and write registry.json.
  const outputDir = path.join(process.cwd(), base.publicOutputDir!)
  await fs.mkdir(outputDir, { recursive: true })

  const registryJsonPath = path.join(outputDir, 'registry.json')
  await fs.writeFile(registryJsonPath, JSON.stringify(fixedRegistry, null, 2))
  await new Promise<void>((resolve, reject) => {
    exec(`pnpm exec prettier --write "${registryJsonPath}"`, (error) => {
      if (error) {
        reject(error)
      }
      else {
        resolve()
      }
    })
  })

  const tempRegistryPath = path.join(process.cwd(), `registry-${base.name}.json`)
  await fs.writeFile(tempRegistryPath, JSON.stringify(fixedRegistry, null, 2))

  return tempRegistryPath
}

/**
 * Build the CLI registry output
 */
async function buildRegistry(base: RegistryBase, tempRegistryPath: string) {
  if (!base.buildMainRegistry) {
    // eslint-disable-next-line no-console
    console.log(`⏭️  Skipping CLI build for ${base.name}`)
    return { success: true, skipped: true }
  }

  // eslint-disable-next-line no-console
  console.log(`🏗️  Building registry with CLI for ${base.name}...`)

  return new Promise((resolve) => {
    // Use local shadcn copy.
    const command = `node ../../packages/cli/dist/index.js build ${tempRegistryPath} --output ${base.publicOutputDir}`
    // eslint-disable-next-line no-console
    console.log(`   Command: ${command}`)

    const process = exec(command)

    // Capture stdout and stderr
    let stdout = ''
    let stderr = ''

    if (process.stdout) {
      process.stdout.on('data', (data) => {
        stdout += data
        // eslint-disable-next-line no-console
        console.log(data.toString().trim())
      })
    }

    if (process.stderr) {
      process.stderr.on('data', (data) => {
        stderr += data
        console.error(data.toString().trim())
      })
    }

    process.on('exit', (code) => {
      if (code === 0) {
        resolve({ success: true })
      }
      else {
        console.error(`\n❌ CLI build failed with code ${code}`)
        if (stderr) {
          console.error('Error output:', stderr)
        }
        if (stdout) {
          // eslint-disable-next-line no-console
          console.log('Output:', stdout)
        }
        console.warn('⚠️  Continuing with rest of build...')
        resolve({ success: false, error: `Process exited with code ${code}` })
      }
    })

    process.on('error', (err) => {
      console.error(`\n❌ Failed to execute CLI command:`, err)
      console.warn('⚠️  Continuing with rest of build...')
      resolve({ success: false, error: err.message })
    })
  })
}

/**
 * Build public index.json
 */
async function buildPublicIndex() {
  rimraf.sync(path.join(process.cwd(), 'public/r/index.json'))
  await fs.writeFile(
    path.join(process.cwd(), 'public/r/index.json'),
    JSON.stringify(ui, null, 2),
  )

  await exec(`eslint --fix public/r/index.json`)
}

/**
 * Build blocks index
 */
async function buildBlocksIndex() {
  const blocks = await getAllBlocks(['registry:block'])

  const payload = blocks.map(block => ({
    name: block.name,
    description: block.description,
    categories: block.categories,
  }))

  rimraf.sync(path.join(process.cwd(), 'registry/__blocks__.json'))
  await fs.writeFile(
    path.join(process.cwd(), 'registry/__blocks__.json'),
    JSON.stringify(payload, null, 2),
  )

  await exec(`eslint --fix registry/__blocks__.json`)
}

/**
 * Build bases index (__index__.ts) that exports all bases registry items
 */
async function buildBasesIndex() {
  // eslint-disable-next-line no-console
  console.log('\n📚 Building registry/bases/__index__.ts...')

  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const Index: Record<string, Record<string, any>> = {\n`

  // Process each base in the configuration
  for (const base of registryConfig) {
    // Skip main registry bases (only include bases from bases/ directory)
    if (base.buildMainRegistry) {
      continue
    }

    const basePath = path.join(process.cwd(), 'registry', base.path)
    if (!existsSync(basePath)) {
      console.warn(`⚠️  Skipping base ${base.name} - path does not exist`)
      continue
    }

    // eslint-disable-next-line no-console
    console.log(`   Processing base: ${base.name}`)

    index += `  ${base.name}: {\n`

    // Collect all registry items from all content types
    for (const contentType of base.contentTypes) {
      const registryFilePath = path.join(process.cwd(), 'registry', contentType.outputFile)

      if (!existsSync(registryFilePath)) {
        console.warn(`   ⚠️  Registry file not found: ${contentType.outputFile}`)
        continue
      }

      try {
        // Dynamically import the registry file
        const registryModule = await import(path.resolve(registryFilePath))
        const items = registryModule[contentType.name] || []

        // Add each item to the index
        for (const item of items) {
          const itemName = item.name
          const itemPath = base.path

          index += `    "${itemName}": {\n`
          index += `      name: "${item.name}",\n`
          index += `      title: "${item.title ?? 'undefined'}",\n`
          index += `      description: "${item.description ?? ''}",\n`
          index += `      type: "${item.type}",\n`
          index += `      registryDependencies: ${JSON.stringify(item.registryDependencies)},\n`
          index += `      files: ${JSON.stringify(item.files?.map((file) => {
            const filePath = typeof file === 'string' ? file : file.path
            // Check if path already starts with content type to avoid duplication
            const pathAlreadyIncludesType = filePath.startsWith(`${contentType.path}/`)
            const fullPath = pathAlreadyIncludesType
              ? `registry/${itemPath}/${filePath}`
              : `registry/${itemPath}/${contentType.path}/${filePath}`
            return {
              path: fullPath,
              type: typeof file === 'string' ? contentType.type || item.type : file.type,
              target: typeof file === 'string' ? '' : (file.target ?? ''),
            }
          }), null, 6).replace(/\n/g, '\n      ')},\n`
          index += `      categories: ${JSON.stringify(item.categories)},\n`
          index += `      meta: ${JSON.stringify(item.meta)},\n`
          index += `    },\n`
        }
      }
      catch (error) {
        console.warn(`   ⚠️  Failed to load registry: ${contentType.outputFile}`, error)
      }
    }

    index += `  },\n`
  }

  index += `}\n`

  // Write the bases index file
  const outputPath = path.join(process.cwd(), 'registry/bases/__index__.ts')
  await fs.mkdir(path.dirname(outputPath), { recursive: true })
  rimraf.sync(outputPath)
  await fs.writeFile(outputPath, index)

  exec(`eslint --fix ${outputPath}`)

  // eslint-disable-next-line no-console
  console.log('   ✅ Bases index generated')
}

/**
 * Main build function
 */
async function main() {
  try {
    // eslint-disable-next-line no-console
    console.log('🚀 Starting dynamic registry build...\n')

    // Process each base in the configuration
    for (const base of registryConfig) {
      await buildBaseRegistry(base)

      if (base.buildMainRegistry) {
        // eslint-disable-next-line no-console
        console.log(`\n🗂️  Building registry/__index__.ts for ${base.name}...`)
        await buildRegistryIndex()

        // eslint-disable-next-line no-console
        console.log(`🗂️  Building registry/__blocks__.json for ${base.name}...`)
        await buildBlocksIndex()

        const tempRegistryPath = await buildRegistryJsonFile(base)

        if (tempRegistryPath) {
          const cliResult = await buildRegistry(base, tempRegistryPath)

          if (cliResult && !cliResult.success && !cliResult.skipped) {
            console.warn(`⚠️  Note: CLI build failed for ${base.name}, but registry files were generated`)
            console.warn(`    You may need to rebuild the CLI: cd packages/cli && pnpm build`)
          }

          // Clean up temp file
          if (existsSync(tempRegistryPath)) {
            await fs.unlink(tempRegistryPath)
          }
        }

        // eslint-disable-next-line no-console
        console.log(`🗂️  Building public/r/index.json for ${base.name}...`)
        await buildPublicIndex()
      }
    }

    // Build the bases index file that exports all bases
    await buildBasesIndex()

    // eslint-disable-next-line no-console
    console.log('\n✅ Registry build complete!')
  }
  catch (error) {
    console.error('❌ Build failed:', error)
    process.exit(1)
  }
}

// Run the build
main()
