export type Library = 'lucide' | 'tabler' | 'hugeicons' | 'phosphor' | 'remixicon'
export const GENERATABLE_LIBRARIES: Library[] = ['lucide', 'tabler', 'hugeicons', 'phosphor', 'remixicon']
export type PlaceholderRecord = Partial<Record<Library, string>>
export type IconMapping = Record<string, Record<string, string>>

export function deriveRawPhosphor(alias: string): string {
  return `Ph${alias.replace(/Icon$/, '')}`
}

export function buildMappingFromRecords(records: PlaceholderRecord[]): {
  mapping: IconMapping
  usage: Record<Library, Set<string>>
  warnings: string[]
} {
  const mapping: IconMapping = {}
  const usage = Object.fromEntries(GENERATABLE_LIBRARIES.map(l => [l, new Set<string>()])) as Record<Library, Set<string>>
  const warnings: string[] = []

  for (const record of records) {
    const canonical = record.lucide
    if (!canonical) {
      warnings.push('IconPlaceholder without a lucide prop')
      continue
    }
    const entry = (mapping[canonical] ??= {})
    for (const library of GENERATABLE_LIBRARIES) {
      const raw = record[library]
      if (!raw)
        continue
      usage[library].add(raw)
      const value = library === 'phosphor' ? deriveRawPhosphor(raw) : raw
      if (entry[library] && entry[library] !== value) {
        warnings.push(`Conflicting ${library} mapping for ${canonical}: keeping ${entry[library]}, ignoring ${value}`)
        continue
      }
      entry[library] = value
    }
  }

  return { mapping, usage, warnings }
}

const LIBRARY_ORDER = ['lucide', 'radix', 'tabler', 'hugeicons', 'phosphor', 'remixicon'] as const

export function mergeLegacy(legacy: IconMapping, scanned: IconMapping): IconMapping {
  const output: IconMapping = {}
  const remaining: IconMapping = { ...scanned }

  for (const [canonical, legacyEntry] of Object.entries(legacy)) {
    const entry: Record<string, string> = { ...legacyEntry }
    const scannedKey
      = canonical in remaining ? canonical : `${canonical}Icon` in remaining ? `${canonical}Icon` : undefined
    if (scannedKey) {
      for (const library of LIBRARY_ORDER) {
        if (!entry[library] && remaining[scannedKey][library]) {
          entry[library] = remaining[scannedKey][library]
        }
      }
      delete remaining[scannedKey]
    }
    output[canonical] = entry
  }

  for (const canonical of Object.keys(remaining).sort()) {
    const entry: Record<string, string> = {}
    for (const library of LIBRARY_ORDER) {
      if (remaining[canonical][library])
        entry[library] = remaining[canonical][library]
    }
    output[canonical] = entry
  }

  return output
}

export const LIBRARY_EXPORT: Record<Library, string> = {
  lucide: '@lucide/vue',
  tabler: '@tabler/icons-vue',
  hugeicons: '@hugeicons/core-free-icons',
  phosphor: '@phosphor-icons/vue',
  remixicon: '@remixicon/vue',
}

export function renderIconFile(library: Library, names: string[]): string {
  const source = LIBRARY_EXPORT[library]
  const lines = [...names].sort().map((name) => {
    if (library === 'phosphor')
      return `export { ${deriveRawPhosphor(name)} as ${name} } from "${source}"`
    return `export { ${name} } from "${source}"`
  })
  return `// Auto-generated by scripts/build-icons.ts\n${lines.join('\n')}\n`
}
