import assert from 'node:assert/strict'
import { it } from 'vitest'
import { buildMappingFromRecords, deriveRawPhosphor, mergeLegacy, renderIconFile } from './build-icons.helpers'

it('deriveRawPhosphor strips Icon suffix and prefixes Ph', () => {
  assert.equal(deriveRawPhosphor('CheckCircleIcon'), 'PhCheckCircle')
  assert.equal(deriveRawPhosphor('WarningIcon'), 'PhWarning')
  assert.equal(deriveRawPhosphor('XIcon'), 'PhX')
  assert.equal(deriveRawPhosphor('CaretDoubleLeftIcon'), 'PhCaretDoubleLeft')
})

it('buildMappingFromRecords keys on lucide value and derives raw phosphor', () => {
  const { mapping, usage } = buildMappingFromRecords([
    { lucide: 'CircleCheckIcon', tabler: 'IconCircleCheck', hugeicons: 'CheckmarkCircle01Icon', phosphor: 'CheckCircleIcon', remixicon: 'RiCheckboxCircleLine' },
  ])
  assert.deepEqual(mapping.CircleCheckIcon, {
    lucide: 'CircleCheckIcon',
    tabler: 'IconCircleCheck',
    hugeicons: 'CheckmarkCircle01Icon',
    phosphor: 'PhCheckCircle',
    remixicon: 'RiCheckboxCircleLine',
  })
  assert.ok(usage.phosphor.has('CheckCircleIcon')) // usage keeps the alias for __phosphor__.ts
  assert.ok(usage.tabler.has('IconCircleCheck'))
})

it('buildMappingFromRecords warns and skips a record without lucide', () => {
  const { mapping, warnings } = buildMappingFromRecords([{ tabler: 'IconX' }])
  assert.equal(Object.keys(mapping).length, 0)
  assert.equal(warnings.length, 1)
})

it('buildMappingFromRecords keeps first on conflict and warns', () => {
  const { mapping, warnings } = buildMappingFromRecords([
    { lucide: 'XIcon', tabler: 'IconX' },
    { lucide: 'XIcon', tabler: 'IconXbox' },
  ])
  assert.equal(mapping.XIcon.tabler, 'IconX')
  assert.ok(warnings.some(w => w.includes('XIcon')))
})

it('mergeLegacy: legacy values win, scan fills only missing libraries', () => {
  const legacy = { Loader2: { lucide: 'Loader2', radix: 'ReloadIcon', tabler: 'IconLoader2', phosphor: 'PhCircleNotch', remixicon: 'RiLoader4Line' } }
  const scanned = { Loader2Icon: { lucide: 'Loader2Icon', tabler: 'IconLoader2', hugeicons: 'Loading03Icon', phosphor: 'PhSpinnerGap', remixicon: 'RiLoader4Line' } }
  const out = mergeLegacy(legacy, scanned)
  assert.equal(out.Loader2.phosphor, 'PhCircleNotch') // legacy wins, NOT PhSpinnerGap
  assert.equal(out.Loader2.hugeicons, 'Loading03Icon') // gap filled from scan
  assert.equal(out.Loader2.radix, 'ReloadIcon') // radix preserved
  assert.ok(!('Loader2Icon' in out)) // scanned key consumed via +Icon bridge
})

it('mergeLegacy: scanned-only canonicals are appended', () => {
  const out = mergeLegacy({}, { CircleCheckIcon: { lucide: 'CircleCheckIcon', phosphor: 'PhCheckCircle' } })
  assert.deepEqual(out.CircleCheckIcon, { lucide: 'CircleCheckIcon', phosphor: 'PhCheckCircle' })
})

it('renderIconFile: plain libraries export the raw name', () => {
  const out = renderIconFile('tabler', ['IconB', 'IconA'])
  assert.equal(out, `// Auto-generated by scripts/build-icons.ts
export { IconA } from "@tabler/icons-vue"
export { IconB } from "@tabler/icons-vue"
`)
})

it('renderIconFile: phosphor aliases raw export to the placeholder alias', () => {
  const out = renderIconFile('phosphor', ['CheckCircleIcon'])
  assert.equal(out, `// Auto-generated by scripts/build-icons.ts
export { PhCheckCircle as CheckCircleIcon } from "@phosphor-icons/vue"
`)
})
