export { default as Message } from "./Message.vue"
export { default as MessageAvatar } from "./MessageAvatar.vue"
export { default as MessageContent } from "./MessageContent.vue"
export { default as MessageFooter } from "./MessageFooter.vue"
export { default as MessageGroup } from "./MessageGroup.vue"
export { default as MessageHeader } from "./MessageHeader.vue"
