name: Setup
description: Installs Node, Enables Corepack and caches pnpm.

runs:
  using: composite

  steps:
    - name: Enable corepack
      run: corepack enable
      shell: bash

    - name: Setup node & pnpm
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: pnpm
