import type { RegistryItem, registryItemTypeSchema } from 'shadcn-vue/schema'
import type { z } from 'zod'
import { existsSync, promises as fs } from 'node:fs'
import path from 'pathe'
import { rimraf } from 'rimraf'
import {
  registryItemSchema,
  registrySchema,
} from 'shadcn-vue/schema'

import { registry } from '../src/registry'
import { buildRegistryV4 as crawlContent } from '../src/registry/crawl-content'
import { styles } from '../src/registry/registry-styles'

const METADATA_NAME = 'metadata.json'
const ROOT_PATH = path.join(process.cwd(), '../v4')
const REGISTRY_PATH = path.join(ROOT_PATH, 'public/r')

const REGISTRY_INDEX_WHITELIST: z.infer<typeof registryItemTypeSchema>[] = [
  'registry:ui',
  'registry:lib',
  'registry:hook',
  'registry:composable',
  'registry:theme',
  'registry:block',
  'registry:example',
]

// ----------------------------------------------------------------------------
// Build registry/__index__.ts.
// ----------------------------------------------------------------------------
async function buildRegistry(registryItems: RegistryItem[]) {
  let index = `/* eslint-disable ts/ban-ts-comment */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry-v4.ts
// Do not edit this file directly.

export const Index: Record<string, any> = {
`

  for (const item of registryItems) {
    const resolveFiles = item.files?.map(
      file =>
        `registry/new-york-v4/${
          typeof file === 'string' ? file : file.path
        }`,
    )
    if (!resolveFiles) {
      continue
    }

    const type = item.type.split(':')[1]

    let componentPath = `@/registry/new-york-v4/${type}/${item.name}`

    if (item.files) {
      const files = item.files.map(file =>
        typeof file === 'string'
          ? { type: 'registry:page', path: file }
          : file,
      )
      if (files?.length) {
        componentPath = `@/registry/new-york-v4/${files[0].path}`
      }
    }

    index += `
"${item.name}": {
  name: "${item.name}",
  description: "${item.description ?? ''}",
  type: "${item.type}",
  registryDependencies: ${JSON.stringify(item.registryDependencies)},
  files: [${item.files?.filter(file => !file.path.includes(METADATA_NAME))?.map((file) => {
    const filePath = `registry/new-york-v4/${
      typeof file === 'string' ? file : file.path
    }`
    const resolvedFilePath = path.resolve(filePath)
    return typeof file === 'string'
      ? `"${resolvedFilePath}"`
      : `{
    path: "${filePath}",
    type: "${file.type}",
    target: "${file.target ?? ''}"
  }`
  })}],
  component: ${
    componentPath
      ? `() => import("${componentPath}").then((m) => m.default)`
      : 'null'
  },
  categories: ${JSON.stringify(item.categories || [])},
  meta: ${JSON.stringify((item as any).meta || {})},
},`
  }

  index += `
}
`

  // ----------------------------------------------------------------------------
  // Build registry/index.json.
  // ----------------------------------------------------------------------------
  const items = registryItems
    .filter(item => ['registry:ui'].includes(item.type))
    .map((item) => {
      return {
        ...item,
        files: item.files?.filter(file => !file.path.includes(METADATA_NAME))?.map((_file) => {
          const file = { path: _file.path, type: item.type }
          return file
        }),
      }
    })
  const registryJson = JSON.stringify(items, null, 2)
  rimraf.sync(path.join(REGISTRY_PATH, 'index.json'))
  await writeFile(
    path.join(REGISTRY_PATH, 'index.json'),
    registryJson,
  )

  // Write registry index.
  rimraf.sync(path.join(ROOT_PATH, 'registry/__index__.ts'))
  await writeFile(path.join(ROOT_PATH, 'registry/__index__.ts'), index)
}

// ----------------------------------------------------------------------------
// Build registry/styles/[style]/[name].json.
// ----------------------------------------------------------------------------
async function buildStyles(registryItems: RegistryItem[]) {
  const styleRegistryPath = path.join(process.cwd(), 'src/public/r')
  const targetPath = path.join(styleRegistryPath, 'styles', 'new-york-v4')

  // Create directory if it doesn't exist.
  if (!existsSync(targetPath)) {
    await fs.mkdir(targetPath, { recursive: true })
  }

  for (const item of registryItems) {
    if (!REGISTRY_INDEX_WHITELIST.includes(item.type)) {
      continue
    }

    let metadata: RegistryItem = {} as any
    let files
    if (item.files) {
      // get metadata.json index and exclude from `files`
      const metadataIndex = item.files.findIndex(_file => _file.path.includes(METADATA_NAME))
      if (metadataIndex !== -1) {
        metadata = JSON.parse(item.files[metadataIndex].content ?? '{}')
      }

      files = await Promise.all(
        item.files.filter((_, index) => index !== metadataIndex).map(async (_file) => {
          const file = {
            path: _file.path,
            type: _file.type,
            content: '',
            target: _file.target ?? '',
          }

          let content: string
          try {
            content = await fs.readFile(
              path.join(process.cwd(), '../v4/registry/new-york-v4', file.path),
              'utf8',
            )
          }
          catch (error) {
            return
          }

          const target = file.target || ''

          return {
            path: file.path,
            type: file.type,
            // replace all reference of `new-york-v4` because it's styling in component is `new-york`
            content: content.replaceAll('/new-york-v4/', '/new-york/'),
            target,
          }
        }),
      )
    }

    const payload = registryItemSchema
      .safeParse({
        ...metadata,
        ...item,
        files,
      })

    if (payload.success) {
      await writeFile(
        path.join(targetPath, `${item.name}.json`),
        JSON.stringify(payload.data, null, 2),
      )
    }
  }

  // ----------------------------------------------------------------------------
  // Build registry/styles/index.json.
  // ----------------------------------------------------------------------------
  const stylesJson = JSON.stringify(styles, null, 2)
  await writeFile(
    path.join(styleRegistryPath, 'styles/index.json'),
    stylesJson,
  )
}

// ----------------------------------------------------------------------------
// Build registry/styles/[name]/index.json.
// ----------------------------------------------------------------------------
async function buildStylesIndex() {
  for (const style of styles) {
    const styleRegistryPath = path.join(process.cwd(), 'src/public/r')
    const targetPath = path.join(styleRegistryPath, 'styles', 'new-york-v4')

    const dependencies = [
      'tw-animate-css',
      'class-variance-authority',
      'lucide-vue-next',
    ]

    const payload: RegistryItem = {
      name: 'index',
      type: 'registry:style',
      dependencies,
      registryDependencies: ['utils'],
      cssVars: {},
      files: [],
    }

    await writeFile(
      path.join(targetPath, 'index.json'),
      JSON.stringify(payload, null, 2),
    )
  }
}

// ----------------------------------------------------------------------------
// Build registry.json file for v4
// ----------------------------------------------------------------------------
async function buildRegistryJsonFile(registryItems: RegistryItem[]) {
  // 1. Fix the path for registry items.
  const fixedRegistry = {
    name: 'v4-registry',
    items: registryItems.map((item) => {
      const files = item.files?.map((file) => {
        return {
          ...file,
          path: `registry/new-york-v4/${file.path}`,
        }
      })

      return {
        ...item,
        files,
      }
    }),
  }

  // 2. Write the content of the registry to `registry.json`
  const registryPath = path.join(ROOT_PATH, 'registry.json')
  rimraf.sync(registryPath)
  await writeFile(registryPath, JSON.stringify(fixedRegistry, null, 2))

  // 3. Copy the registry.json to the www/public/r/styles/new-york-v4 directory.
  const wwwTargetPath = path.join(
    process.cwd(),
    'src/public/r/styles/new-york-v4/registry.json',
  )
  await fs.mkdir(path.dirname(wwwTargetPath), { recursive: true })
  await fs.cp(registryPath, wwwTargetPath)
}

// ----------------------------------------------------------------------------
// Build blocks index
// ----------------------------------------------------------------------------
async function buildBlocksIndex(registryItems: RegistryItem[]) {
  const blocks = registryItems.filter(item => item.type === 'registry:block')

  const payload = blocks.map(block => ({
    name: block.name,
    description: block.description,
    categories: block.categories || [],
  }))

  const blocksPath = path.join(ROOT_PATH, 'registry/__blocks__.json')
  rimraf.sync(blocksPath)
  await writeFile(blocksPath, JSON.stringify(payload, null, 2))
}

async function writeFile(filepath: string, payload: any) {
  // Ensure directory exists
  await fs.mkdir(path.dirname(filepath), { recursive: true })
  return fs.writeFile(
    filepath,
    `${payload}\r\n`,
    'utf8',
  )
}

// ----------------------------------------------------------------------------
// Main execution
// ----------------------------------------------------------------------------
async function main() {
  try {
    const content = await crawlContent()
    const result = registrySchema.safeParse([...registry.items, ...content])

    if (!result.success) {
      console.error(result.error)
      process.exit(1)
    }

    // eslint-disable-next-line no-console
    console.log('🗂️ Building registry/__index__.ts...')
    await buildRegistry(result.data.items)

    // eslint-disable-next-line no-console
    console.log('🗂️ Building registry/__blocks__.json...')
    await buildBlocksIndex(result.data.items)

    // eslint-disable-next-line no-console
    console.log('💅 Building registry.json...')
    await buildRegistryJsonFile(result.data.items)

    // eslint-disable-next-line no-console
    console.log('🎨 Building styles...')
    await buildStyles(result.data.items)
    await buildStylesIndex()

    // eslint-disable-next-line no-console
    console.log('✅ V4 registry built successfully!')
    // eslint-disable-next-line no-console
    console.log(`#️⃣ ${result.data.items.length} items processed`)
  }
  catch (error) {
    console.error('❌ Error building V4 registry:', error)
    process.exit(1)
  }
}

main()
