// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const Index: Record<string, any> = {

"utils": {
  name: "utils",
  description: "",
  type: "registry:lib",
  registryDependencies: undefined,
  files: [{
    path: "registry/new-york-v4/lib/utils.ts",
    type: "registry:lib",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"accordion": {
  name: "accordion",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/accordion/Accordion.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/accordion/AccordionContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/accordion/AccordionItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/accordion/AccordionTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/accordion/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"alert": {
  name: "alert",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/alert/Alert.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert/AlertDescription.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert/AlertTitle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"alert-dialog": {
  name: "alert-dialog",
  description: "",
  type: "registry:ui",
  registryDependencies: ["button"],
  files: [{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialog.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialogAction.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialogCancel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialogContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialogDescription.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialogFooter.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialogHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialogTitle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialogTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"aspect-ratio": {
  name: "aspect-ratio",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/aspect-ratio/AspectRatio.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/aspect-ratio/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"avatar": {
  name: "avatar",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/avatar/Avatar.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/avatar/AvatarFallback.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/avatar/AvatarImage.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/avatar/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"badge": {
  name: "badge",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/badge/Badge.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/badge/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"breadcrumb": {
  name: "breadcrumb",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/breadcrumb/Breadcrumb.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/breadcrumb/BreadcrumbEllipsis.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/breadcrumb/BreadcrumbItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/breadcrumb/BreadcrumbLink.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/breadcrumb/BreadcrumbList.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/breadcrumb/BreadcrumbPage.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/breadcrumb/BreadcrumbSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/breadcrumb/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"button": {
  name: "button",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/button/Button.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/button/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"calendar": {
  name: "calendar",
  description: "",
  type: "registry:ui",
  registryDependencies: ["button"],
  files: [{
    path: "registry/new-york-v4/ui/calendar/Calendar.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarCell.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarCellTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarGrid.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarGridBody.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarGridHead.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarGridRow.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarHeadCell.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarHeading.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarNextButton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarPrevButton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"card": {
  name: "card",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/card/Card.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/card/CardAction.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/card/CardContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/card/CardDescription.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/card/CardFooter.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/card/CardHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/card/CardTitle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/card/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"carousel": {
  name: "carousel",
  description: "",
  type: "registry:ui",
  registryDependencies: ["button"],
  files: [{
    path: "registry/new-york-v4/ui/carousel/Carousel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/carousel/CarouselContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/carousel/CarouselItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/carousel/CarouselNext.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/carousel/CarouselPrevious.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/carousel/index.ts",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/carousel/interface.ts",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/carousel/useCarousel.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"chart": {
  name: "chart",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/chart/ChartContainer.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/chart/ChartLegendContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/chart/ChartStyle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/chart/ChartTooltipContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/chart/ChartTooltipLabel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/chart/index.ts",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/chart/utils.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"checkbox": {
  name: "checkbox",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/checkbox/Checkbox.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/checkbox/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"collapsible": {
  name: "collapsible",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/collapsible/Collapsible.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/collapsible/CollapsibleContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/collapsible/CollapsibleTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/collapsible/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"combobox": {
  name: "combobox",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/combobox/Combobox.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxAnchor.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxEmpty.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxInput.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxItemIndicator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxList.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxViewport.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"command": {
  name: "command",
  description: "",
  type: "registry:ui",
  registryDependencies: ["dialog"],
  files: [{
    path: "registry/new-york-v4/ui/command/Command.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/CommandDialog.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/CommandEmpty.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/CommandGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/CommandInput.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/CommandItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/CommandList.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/CommandSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/CommandShortcut.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"context-menu": {
  name: "context-menu",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/context-menu/ContextMenu.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuCheckboxItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuLabel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuPortal.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuRadioGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuRadioItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuShortcut.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuSub.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuSubContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuSubTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"dialog": {
  name: "dialog",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/dialog/Dialog.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogClose.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogDescription.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogFooter.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogOverlay.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogScrollContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogTitle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"drawer": {
  name: "drawer",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/drawer/Drawer.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/DrawerClose.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/DrawerContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/DrawerDescription.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/DrawerFooter.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/DrawerHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/DrawerOverlay.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/DrawerTitle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/DrawerTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"dropdown-menu": {
  name: "dropdown-menu",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenu.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuCheckboxItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuLabel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuRadioGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuRadioItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuShortcut.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuSub.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuSubContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuSubTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"form": {
  name: "form",
  description: "",
  type: "registry:ui",
  registryDependencies: ["label"],
  files: [{
    path: "registry/new-york-v4/ui/form/FormControl.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/form/FormDescription.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/form/FormItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/form/FormLabel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/form/FormMessage.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/form/index.ts",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/form/injectionKeys.ts",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/form/useFormField.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"hover-card": {
  name: "hover-card",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/hover-card/HoverCard.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/hover-card/HoverCardContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/hover-card/HoverCardTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/hover-card/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"input": {
  name: "input",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/input/Input.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/input/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"label": {
  name: "label",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/label/Label.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/label/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"menubar": {
  name: "menubar",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/menubar/Menubar.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarCheckboxItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarLabel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarMenu.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarRadioGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarRadioItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarShortcut.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarSub.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarSubContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarSubTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"navigation-menu": {
  name: "navigation-menu",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/navigation-menu/NavigationMenu.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/navigation-menu/NavigationMenuContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/navigation-menu/NavigationMenuIndicator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/navigation-menu/NavigationMenuItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/navigation-menu/NavigationMenuLink.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/navigation-menu/NavigationMenuList.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/navigation-menu/NavigationMenuTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/navigation-menu/NavigationMenuViewport.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/navigation-menu/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"number-field": {
  name: "number-field",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/number-field/NumberField.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/number-field/NumberFieldContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/number-field/NumberFieldDecrement.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/number-field/NumberFieldIncrement.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/number-field/NumberFieldInput.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/number-field/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"pagination": {
  name: "pagination",
  description: "",
  type: "registry:ui",
  registryDependencies: ["button"],
  files: [{
    path: "registry/new-york-v4/ui/pagination/Pagination.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pagination/PaginationContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pagination/PaginationEllipsis.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pagination/PaginationFirst.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pagination/PaginationItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pagination/PaginationLast.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pagination/PaginationNext.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pagination/PaginationPrevious.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pagination/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"pin-input": {
  name: "pin-input",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/pin-input/PinInput.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pin-input/PinInputGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pin-input/PinInputSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pin-input/PinInputSlot.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pin-input/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"popover": {
  name: "popover",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/popover/Popover.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/popover/PopoverAnchor.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/popover/PopoverContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/popover/PopoverTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/popover/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"progress": {
  name: "progress",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/progress/Progress.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/progress/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"radio-group": {
  name: "radio-group",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/radio-group/RadioGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/radio-group/RadioGroupItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/radio-group/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"range-calendar": {
  name: "range-calendar",
  description: "",
  type: "registry:ui",
  registryDependencies: ["button"],
  files: [{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendar.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarCell.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarCellTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarGrid.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarGridBody.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarGridHead.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarGridRow.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarHeadCell.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarHeading.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarNextButton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarPrevButton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"resizable": {
  name: "resizable",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/resizable/ResizableHandle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/resizable/ResizablePanel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/resizable/ResizablePanelGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/resizable/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"scroll-area": {
  name: "scroll-area",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/scroll-area/ScrollArea.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/scroll-area/ScrollBar.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/scroll-area/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"select": {
  name: "select",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/select/Select.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectItemText.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectLabel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectScrollDownButton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectScrollUpButton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectValue.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"separator": {
  name: "separator",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/separator/Separator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/separator/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sheet": {
  name: "sheet",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/sheet/Sheet.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/SheetClose.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/SheetContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/SheetDescription.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/SheetFooter.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/SheetHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/SheetOverlay.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/SheetTitle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/SheetTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sidebar": {
  name: "sidebar",
  description: "",
  type: "registry:ui",
  registryDependencies: ["sheet","input","tooltip","skeleton","separator","button"],
  files: [{
    path: "registry/new-york-v4/ui/sidebar/Sidebar.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarFooter.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarGroupAction.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarGroupContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarGroupLabel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarInput.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarInset.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenu.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuAction.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuBadge.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuButton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuButtonChild.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuSkeleton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuSub.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuSubButton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuSubItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarProvider.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarRail.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/index.ts",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/utils.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"skeleton": {
  name: "skeleton",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/skeleton/Skeleton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/skeleton/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"slider": {
  name: "slider",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/slider/Slider.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/slider/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sonner": {
  name: "sonner",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/sonner/Sonner.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sonner/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"stepper": {
  name: "stepper",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/stepper/Stepper.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/stepper/StepperDescription.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/stepper/StepperIndicator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/stepper/StepperItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/stepper/StepperSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/stepper/StepperTitle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/stepper/StepperTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/stepper/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"switch": {
  name: "switch",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/switch/Switch.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/switch/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"table": {
  name: "table",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/table/Table.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/TableBody.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/TableCaption.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/TableCell.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/TableEmpty.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/TableFooter.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/TableHead.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/TableHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/TableRow.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/index.ts",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/utils.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"tabs": {
  name: "tabs",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/tabs/Tabs.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tabs/TabsContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tabs/TabsList.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tabs/TabsTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tabs/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"tags-input": {
  name: "tags-input",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/tags-input/TagsInput.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tags-input/TagsInputInput.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tags-input/TagsInputItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tags-input/TagsInputItemDelete.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tags-input/TagsInputItemText.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tags-input/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"textarea": {
  name: "textarea",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/textarea/Textarea.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/textarea/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"toggle": {
  name: "toggle",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/toggle/Toggle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/toggle/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"toggle-group": {
  name: "toggle-group",
  description: "",
  type: "registry:ui",
  registryDependencies: ["toggle"],
  files: [{
    path: "registry/new-york-v4/ui/toggle-group/ToggleGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/toggle-group/ToggleGroupItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/toggle-group/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"tooltip": {
  name: "tooltip",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/tooltip/Tooltip.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tooltip/TooltipContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tooltip/TooltipProvider.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tooltip/TooltipTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tooltip/index.ts",
    type: "registry:ui",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"login-01": {
  name: "login-01",
  description: "",
  type: "registry:block",
  registryDependencies: ["button","card","input","label"],
  files: [{
    path: "registry/new-york-v4/blocks/login-01/page.vue",
    type: "registry:page",
    target: "pages/login/index.vue"
  },{
    path: "registry/new-york-v4/blocks/login-01/components/LoginForm.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"login-02": {
  name: "login-02",
  description: "",
  type: "registry:block",
  registryDependencies: ["button","input","label"],
  files: [{
    path: "registry/new-york-v4/blocks/login-02/page.vue",
    type: "registry:page",
    target: "pages/login/index.vue"
  },{
    path: "registry/new-york-v4/blocks/login-02/components/LoginForm.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"login-03": {
  name: "login-03",
  description: "",
  type: "registry:block",
  registryDependencies: ["button","card","input","label"],
  files: [{
    path: "registry/new-york-v4/blocks/login-03/page.vue",
    type: "registry:page",
    target: "pages/login/index.vue"
  },{
    path: "registry/new-york-v4/blocks/login-03/components/LoginForm.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"login-04": {
  name: "login-04",
  description: "",
  type: "registry:block",
  registryDependencies: ["button","card","input","label"],
  files: [{
    path: "registry/new-york-v4/blocks/login-04/page.vue",
    type: "registry:page",
    target: "pages/login/index.vue"
  },{
    path: "registry/new-york-v4/blocks/login-04/components/LoginForm.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"login-05": {
  name: "login-05",
  description: "",
  type: "registry:block",
  registryDependencies: ["button","input","label"],
  files: [{
    path: "registry/new-york-v4/blocks/login-05/page.vue",
    type: "registry:page",
    target: "pages/login/index.vue"
  },{
    path: "registry/new-york-v4/blocks/login-05/components/LoginForm.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"products-01": {
  name: "products-01",
  description: "",
  type: "registry:block",
  registryDependencies: ["badge","button","checkbox","dropdown-menu","pagination","select","table","tabs"],
  files: [{
    path: "registry/new-york-v4/blocks/products-01/page.vue",
    type: "registry:page",
    target: "pages/products/index.vue"
  },{
    path: "registry/new-york-v4/blocks/products-01/components/ProductsTable.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sidebar-01": {
  name: "sidebar-01",
  description: "",
  type: "registry:block",
  registryDependencies: ["breadcrumb","separator","sidebar","label","dropdown-menu"],
  files: [{
    path: "registry/new-york-v4/blocks/sidebar-01/page.vue",
    type: "registry:page",
    target: "pages/sidebar/index.vue"
  },{
    path: "registry/new-york-v4/blocks/sidebar-01/components/AppSidebar.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-01/components/SearchForm.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-01/components/VersionSwitcher.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sidebar-02": {
  name: "sidebar-02",
  description: "",
  type: "registry:block",
  registryDependencies: ["breadcrumb","separator","sidebar","collapsible","label","dropdown-menu"],
  files: [{
    path: "registry/new-york-v4/blocks/sidebar-02/page.vue",
    type: "registry:page",
    target: "pages/sidebar/index.vue"
  },{
    path: "registry/new-york-v4/blocks/sidebar-02/components/AppSidebar.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-02/components/SearchForm.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-02/components/VersionSwitcher.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sidebar-03": {
  name: "sidebar-03",
  description: "",
  type: "registry:block",
  registryDependencies: ["breadcrumb","separator","sidebar"],
  files: [{
    path: "registry/new-york-v4/blocks/sidebar-03/page.vue",
    type: "registry:page",
    target: "pages/sidebar/index.vue"
  },{
    path: "registry/new-york-v4/blocks/sidebar-03/components/AppSidebar.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sidebar-04": {
  name: "sidebar-04",
  description: "",
  type: "registry:block",
  registryDependencies: ["breadcrumb","separator","sidebar"],
  files: [{
    path: "registry/new-york-v4/blocks/sidebar-04/page.vue",
    type: "registry:page",
    target: "pages/sidebar/index.vue"
  },{
    path: "registry/new-york-v4/blocks/sidebar-04/components/AppSidebar.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sidebar-05": {
  name: "sidebar-05",
  description: "",
  type: "registry:block",
  registryDependencies: ["breadcrumb","separator","sidebar","collapsible","label"],
  files: [{
    path: "registry/new-york-v4/blocks/sidebar-05/page.vue",
    type: "registry:page",
    target: "pages/sidebar/index.vue"
  },{
    path: "registry/new-york-v4/blocks/sidebar-05/components/AppSidebar.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-05/components/SearchForm.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sidebar-06": {
  name: "sidebar-06",
  description: "",
  type: "registry:block",
  registryDependencies: ["breadcrumb","separator","sidebar","dropdown-menu","button","card"],
  files: [{
    path: "registry/new-york-v4/blocks/sidebar-06/page.vue",
    type: "registry:page",
    target: "pages/sidebar/index.vue"
  },{
    path: "registry/new-york-v4/blocks/sidebar-06/components/AppSidebar.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-06/components/NavMain.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-06/components/SidebarOptInForm.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sidebar-07": {
  name: "sidebar-07",
  description: "",
  type: "registry:block",
  registryDependencies: ["breadcrumb","separator","sidebar","collapsible","dropdown-menu","avatar"],
  files: [{
    path: "registry/new-york-v4/blocks/sidebar-07/page.vue",
    type: "registry:page",
    target: "pages/sidebar/index.vue"
  },{
    path: "registry/new-york-v4/blocks/sidebar-07/components/AppSidebar.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-07/components/NavMain.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-07/components/NavProjects.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-07/components/NavUser.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-07/components/TeamSwitcher.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sidebar-08": {
  name: "sidebar-08",
  description: "",
  type: "registry:block",
  registryDependencies: ["breadcrumb","separator","sidebar","collapsible","dropdown-menu","avatar"],
  files: [{
    path: "registry/new-york-v4/blocks/sidebar-08/page.vue",
    type: "registry:page",
    target: "pages/sidebar/index.vue"
  },{
    path: "registry/new-york-v4/blocks/sidebar-08/components/AppSidebar.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-08/components/NavMain.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-08/components/NavProjects.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-08/components/NavSecondary.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-08/components/NavUser.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sidebar-09": {
  name: "sidebar-09",
  description: "",
  type: "registry:block",
  registryDependencies: ["breadcrumb","separator","sidebar","label","switch","avatar","dropdown-menu"],
  files: [{
    path: "registry/new-york-v4/blocks/sidebar-09/page.vue",
    type: "registry:page",
    target: "pages/sidebar/index.vue"
  },{
    path: "registry/new-york-v4/blocks/sidebar-09/components/AppSidebar.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-09/components/NavUser.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sidebar-10": {
  name: "sidebar-10",
  description: "",
  type: "registry:block",
  registryDependencies: ["breadcrumb","separator","sidebar","button","popover","dropdown-menu","collapsible"],
  files: [{
    path: "registry/new-york-v4/blocks/sidebar-10/page.vue",
    type: "registry:page",
    target: "pages/sidebar/index.vue"
  },{
    path: "registry/new-york-v4/blocks/sidebar-10/components/AppSidebar.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-10/components/NavActions.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-10/components/NavFavorites.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-10/components/NavMain.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-10/components/NavSecondary.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-10/components/NavWorkspaces.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-10/components/TeamSwitcher.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sidebar-11": {
  name: "sidebar-11",
  description: "",
  type: "registry:block",
  registryDependencies: ["breadcrumb","separator","sidebar","collapsible"],
  files: [{
    path: "registry/new-york-v4/blocks/sidebar-11/page.vue",
    type: "registry:page",
    target: "pages/sidebar/index.vue"
  },{
    path: "registry/new-york-v4/blocks/sidebar-11/components/AppSidebar.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-11/components/Tree.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sidebar-12": {
  name: "sidebar-12",
  description: "",
  type: "registry:block",
  registryDependencies: ["breadcrumb","separator","sidebar","collapsible","calendar","avatar","dropdown-menu"],
  files: [{
    path: "registry/new-york-v4/blocks/sidebar-12/page.vue",
    type: "registry:page",
    target: "pages/sidebar/index.vue"
  },{
    path: "registry/new-york-v4/blocks/sidebar-12/components/AppSidebar.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-12/components/Calendars.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-12/components/DatePicker.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-12/components/NavUser.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sidebar-13": {
  name: "sidebar-13",
  description: "",
  type: "registry:block",
  registryDependencies: ["breadcrumb","button","dialog","sidebar"],
  files: [{
    path: "registry/new-york-v4/blocks/sidebar-13/page.vue",
    type: "registry:page",
    target: "pages/sidebar/index.vue"
  },{
    path: "registry/new-york-v4/blocks/sidebar-13/components/SettingsDialog.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sidebar-14": {
  name: "sidebar-14",
  description: "",
  type: "registry:block",
  registryDependencies: ["breadcrumb","sidebar"],
  files: [{
    path: "registry/new-york-v4/blocks/sidebar-14/page.vue",
    type: "registry:page",
    target: "pages/sidebar/index.vue"
  },{
    path: "registry/new-york-v4/blocks/sidebar-14/components/AppSidebar.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sidebar-15": {
  name: "sidebar-15",
  description: "",
  type: "registry:block",
  registryDependencies: ["breadcrumb","separator","sidebar","collapsible","calendar","dropdown-menu","avatar"],
  files: [{
    path: "registry/new-york-v4/blocks/sidebar-15/page.vue",
    type: "registry:page",
    target: "pages/sidebar/index.vue"
  },{
    path: "registry/new-york-v4/blocks/sidebar-15/components/AppSidebar.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-15/components/Calendars.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-15/components/DatePicker.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-15/components/NavFavorites.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-15/components/NavMain.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-15/components/NavSecondary.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-15/components/NavUser.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-15/components/NavWorkspaces.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-15/components/SidebarLeft.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-15/components/SidebarRight.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-15/components/TeamSwitcher.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"sidebar-16": {
  name: "sidebar-16",
  description: "",
  type: "registry:block",
  registryDependencies: ["sidebar","collapsible","dropdown-menu","avatar","label","breadcrumb","button","separator"],
  files: [{
    path: "registry/new-york-v4/blocks/sidebar-16/page.vue",
    type: "registry:page",
    target: "pages/sidebar/index.vue"
  },{
    path: "registry/new-york-v4/blocks/sidebar-16/components/AppSidebar.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-16/components/NavMain.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-16/components/NavProjects.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-16/components/NavSecondary.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-16/components/NavUser.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-16/components/SearchForm.vue",
    type: "registry:component",
    target: ""
  },{
    path: "registry/new-york-v4/blocks/sidebar-16/components/SiteHeader.vue",
    type: "registry:component",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartAreaAxes": {
  name: "ChartAreaAxes",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartAreaAxes.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartAreaGradient": {
  name: "ChartAreaGradient",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartAreaGradient.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartAreaIcons": {
  name: "ChartAreaIcons",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartAreaIcons.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartAreaInteractive": {
  name: "ChartAreaInteractive",
  description: "",
  type: "registry:block",
  registryDependencies: ["card","chart","select"],
  files: [{
    path: "registry/new-york-v4/charts/ChartAreaInteractive.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartBarDefault": {
  name: "ChartBarDefault",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartBarDefault.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartBarHorizontal": {
  name: "ChartBarHorizontal",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartBarHorizontal.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartBarInteractive": {
  name: "ChartBarInteractive",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartBarInteractive.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartBarMultiple": {
  name: "ChartBarMultiple",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartBarMultiple.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartLineDefault": {
  name: "ChartLineDefault",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartLineDefault.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartLineInteractive": {
  name: "ChartLineInteractive",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartLineInteractive.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartLineLinear": {
  name: "ChartLineLinear",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartLineLinear.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartLineStep": {
  name: "ChartLineStep",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartLineStep.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartPieDonut": {
  name: "ChartPieDonut",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartPieDonut.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartPieDonutText": {
  name: "ChartPieDonutText",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartPieDonutText.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartPieSimple": {
  name: "ChartPieSimple",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartPieSimple.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartPieStacked": {
  name: "ChartPieStacked",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartPieStacked.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartTooltipDefault": {
  name: "ChartTooltipDefault",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartTooltipDefault.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartTooltipIcons": {
  name: "ChartTooltipIcons",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartTooltipIcons.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartTooltipIndicatorLine": {
  name: "ChartTooltipIndicatorLine",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartTooltipIndicatorLine.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartTooltipIndicatorNone": {
  name: "ChartTooltipIndicatorNone",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartTooltipIndicatorNone.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartTooltipLabelCustom": {
  name: "ChartTooltipLabelCustom",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartTooltipLabelCustom.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartTooltipLabelFormatter": {
  name: "ChartTooltipLabelFormatter",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartTooltipLabelFormatter.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
"ChartTooltipLabelNone": {
  name: "ChartTooltipLabelNone",
  description: "",
  type: "registry:block",
  registryDependencies: ["chart","card"],
  files: [{
    path: "registry/new-york-v4/charts/ChartTooltipLabelNone.vue",
    type: "registry:block",
    target: ""
  }],
  source: "",
  category: "",
  subcategory: ""
},
}

