import type { RegistryItem } from "shadcn-vue/schema"

export const fonts = [
  {
    name: "font-geist-sans",
    title: "Geist Sans",
    type: "registry:font",
    font: {
      family: "'Geist Variable', sans-serif",
      provider: "google",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Geist",
    },
  },
  {
    name: "font-inter",
    title: "Inter",
    type: "registry:font",
    font: {
      family: "'Inter Variable', sans-serif",
      provider: "google",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Inter",
    },
  },
  {
    name: "font-noto-sans",
    title: "Noto Sans",
    type: "registry:font",
    font: {
      family: "'Noto Sans Variable', sans-serif",
      provider: "google",
      variable: "--font-sans",
      import: "Noto_Sans",
    },
  },
  {
    name: "font-nunito-sans",
    title: "Nunito Sans",
    type: "registry:font",
    font: {
      family: "'Nunito Sans Variable', sans-serif",
      provider: "google",
      variable: "--font-sans",
      import: "Nunito_Sans",
    },
  },
  {
    name: "font-figtree",
    title: "Figtree",
    type: "registry:font",
    font: {
      family: "'Figtree Variable', sans-serif",
      provider: "google",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Figtree",
    },
  },
  {
    name: "font-roboto",
    title: "Roboto",
    type: "registry:font",
    font: {
      family: "'Roboto', sans-serif",
      provider: "google",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Roboto",
    },
  },
  {
    name: "font-raleway",
    title: "Raleway",
    type: "registry:font",
    font: {
      family: "'Raleway', sans-serif",
      provider: "google",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Raleway",
    },
  },
  {
    name: "font-dm-sans",
    title: "DM Sans",
    type: "registry:font",
    font: {
      family: "'DM Sans', sans-serif",
      provider: "google",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "DM_Sans",
    },
  },
  {
    name: "font-public-sans",
    title: "Public Sans",
    type: "registry:font",
    font: {
      family: "'Public Sans', sans-serif",
      provider: "google",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Public_Sans",
    },
  },
  {
    name: "font-outfit",
    title: "Outfit",
    type: "registry:font",
    font: {
      family: "'Outfit', sans-serif",
      provider: "google",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Outfit",
    },
  },
  {
    name: "font-jetbrains-mono",
    title: "JetBrains Mono",
    type: "registry:font",
    font: {
      family: "'JetBrains Mono Variable', monospace",
      provider: "google",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "JetBrains_Mono",
    },
  },
  {
    name: "font-playfair-display",
    title: "Playfair Display",
    type: "registry:font",
    font: {
      family: "'Playfair Display Variable', serif",
      provider: "google",
      variable: "--font-serif",
      subsets: ["latin"],
      import: "Playfair_Display",
    },
  },
  {
    name: "font-oxanium",
    title: "Oxanium",
    type: "registry:font",
    font: {
      family: "'Oxanium Variable', sans-serif",
      provider: "google",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Oxanium",
    },
  },
  {
    name: "font-manrope",
    title: "Manrope",
    type: "registry:font",
    font: {
      family: "'Manrope Variable', sans-serif",
      provider: "google",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Manrope",
    },
  },
  {
    name: "font-space-grotesk",
    title: "Space Grotesk",
    type: "registry:font",
    font: {
      family: "'Space Grotesk Variable', sans-serif",
      provider: "google",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Space_Grotesk",
    },
  },
  {
    name: "font-montserrat",
    title: "Montserrat",
    type: "registry:font",
    font: {
      family: "'Montserrat Variable', sans-serif",
      provider: "google",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Montserrat",
    },
  },
  {
    name: "font-ibm-plex-sans",
    title: "IBM Plex Sans",
    type: "registry:font",
    font: {
      family: "'IBM Plex Sans', sans-serif",
      provider: "google",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "IBM_Plex_Sans",
    },
  },
  {
    name: "font-source-sans-3",
    title: "Source Sans 3",
    type: "registry:font",
    font: {
      family: "'Source Sans 3 Variable', sans-serif",
      provider: "google",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Source_Sans_3",
    },
  },
  {
    name: "font-instrument-sans",
    title: "Instrument Sans",
    type: "registry:font",
    font: {
      family: "'Instrument Sans Variable', sans-serif",
      provider: "google",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Instrument_Sans",
    },
  },
  {
    name: "font-geist-mono",
    title: "Geist Mono",
    type: "registry:font",
    font: {
      family: "'Geist Mono Variable', monospace",
      provider: "google",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Geist_Mono",
    },
  },
  {
    name: "font-noto-serif",
    title: "Noto Serif",
    type: "registry:font",
    font: {
      family: "'Noto Serif Variable', serif",
      provider: "google",
      variable: "--font-serif",
      subsets: ["latin"],
      import: "Noto_Serif",
    },
  },
  {
    name: "font-roboto-slab",
    title: "Roboto Slab",
    type: "registry:font",
    font: {
      family: "'Roboto Slab Variable', serif",
      provider: "google",
      variable: "--font-serif",
      subsets: ["latin"],
      import: "Roboto_Slab",
    },
  },
  {
    name: "font-merriweather",
    title: "Merriweather",
    type: "registry:font",
    font: {
      family: "'Merriweather Variable', serif",
      provider: "google",
      variable: "--font-serif",
      subsets: ["latin"],
      import: "Merriweather",
    },
  },
  {
    name: "font-lora",
    title: "Lora",
    type: "registry:font",
    font: {
      family: "'Lora Variable', serif",
      provider: "google",
      variable: "--font-serif",
      subsets: ["latin"],
      import: "Lora",
    },
  },
] satisfies RegistryItem[]
