import { exec } from 'node:child_process'
import { promises as fs } from 'node:fs'
import path from 'node:path'
import { promisify } from 'node:util'
import { rimraf } from 'rimraf'
import { lib as rekaLibItems } from '@/registry/bases/reka/lib/_registry'
import { ui as rekaUiItems } from '@/registry/bases/reka/ui/_registry'
import { STYLES } from '@/registry/styles'

const execAsync = promisify(exec)

/**
 * Mirrors shadcn-ui's `buildRegistryJsonFile` + `buildRegistry` flow for the
 * per-style outputs. For each `reka-<style>` combination we:
 *
 *   1. Take the authored `bases/reka/ui` registry items (one entry per
 *      component with its dependencies + file list)
 *   2. Rewrite each file's `path` from `ui/<comp>/<file>` to
 *      `styles/reka-<style>/ui/<comp>/<file>` so the local shadcn-vue CLI
 *      reads from the codegen'd output (where `cn-*` tokens are already
 *      expanded and IconPlaceholder is already replaced with @lucide/vue)
 *   3. Write `apps/v4/public/r/styles/reka-<style>/registry.json`
 *   4. Write a temporary `apps/v4/registry-reka-<style>.json` at the project
 *      root (the CLI's `build` command takes a JSON file path as input)
 *   5. Spawn the local shadcn-vue CLI to emit per-component JSONs at
 *      `public/r/styles/reka-<style>/<name>.json`
 *   6. Remove the temp registry file
 *
 * This must run AFTER `buildStyles()` (which produces `apps/v4/styles/reka-*`)
 * because the CLI reads file content from disk at those paths.
 *
 * Scope: `registry:ui` and `registry:lib` items. Examples, blocks, fonts,
 * hooks are out-of-scope until per-style example/block sources exist.
 */

const SOURCE_BASE = 'reka'
const REGISTRY_NAME = 'shadcn-vue'
const REGISTRY_HOMEPAGE = 'https://shadcn-vue.com'
const PUBLIC_OUTPUT_BASE = 'public/r/styles'
const CLI_RELATIVE_PATH = '../../packages/cli/dist/index.js'

interface RegistryFile {
  path: string
  type: string
  target?: string
}

interface RegistryItem {
  name: string
  type: string
  files?: RegistryFile[]
  [key: string]: unknown
}

function rewriteFilePath(originalPath: string, styleDir: string): string {
  // Source paths are like `ui/accordion/Accordion.vue`. We need them rooted
  // at the per-style codegen output directory so the CLI can read the file.
  // The CLI runs with cwd = apps/v4, so the path must be relative to apps/v4.
  return `styles/${styleDir}/${originalPath}`
}

async function publishStyle(styleName: string) {
  const styleDir = `${SOURCE_BASE}-${styleName}`
  const cwd = process.cwd()

  // Rewrite each item's file paths to point at the codegen'd per-style copy.
  // UI items live under `styles/reka-<style>/ui/…` (generated by buildStyles).
  // Lib items don't need style-specific transforms, so they read directly from
  // the shared base source at `registry/bases/reka/lib/…`.
  const uiItems = (rekaUiItems as RegistryItem[]).map((item) => {
    const files = (item.files ?? []).map(file => ({
      ...file,
      path: rewriteFilePath(file.path, styleDir),
    }))
    return { ...item, files }
  })

  const libItems = (rekaLibItems as RegistryItem[]).map((item) => {
    const files = (item.files ?? []).map(file => ({
      ...file,
      path: `registry/bases/${SOURCE_BASE}/${file.path}`,
    }))
    return { ...item, files }
  })

  // The CLI's init flow fetches `styles/<style>/index.json` to install base
  // dependencies, the cn() util, and the Tailwind v4 animation plugin.
  // `@lucide/vue` is reconciled against the user's chosen icon library by
  // packages/cli/src/utils/icon-libraries.ts, so listing it here is safe.
  const indexItem: RegistryItem = {
    name: 'index',
    type: 'registry:style',
    dependencies: ['class-variance-authority', '@lucide/vue'],
    devDependencies: ['tw-animate-css'],
    registryDependencies: ['utils'],
    files: [],
    cssVars: {},
  }

  const items = [indexItem, ...uiItems, ...libItems]

  const registry = {
    name: REGISTRY_NAME,
    homepage: REGISTRY_HOMEPAGE,
    items,
  }

  // 1. Write the human-readable registry.json into public/r/styles/<dir>/.
  const publicDir = path.join(cwd, PUBLIC_OUTPUT_BASE, styleDir)
  await fs.mkdir(publicDir, { recursive: true })
  const publicRegistryPath = path.join(publicDir, 'registry.json')
  await fs.writeFile(
    publicRegistryPath,
    `${JSON.stringify(registry, null, 2)}\n`,
    'utf8',
  )

  // 2. Write a temp registry file at the project root for the CLI to consume.
  //    The CLI's `build` command takes a JSON file path as its first argument.
  const tempRegistryPath = path.join(cwd, `registry-${styleDir}.json`)
  await fs.writeFile(
    tempRegistryPath,
    JSON.stringify(registry, null, 2),
    'utf8',
  )

  // 3. Spawn the local shadcn-vue CLI to emit per-component JSONs.
  try {
    const command = `node ${CLI_RELATIVE_PATH} build ${tempRegistryPath} --output ${PUBLIC_OUTPUT_BASE}/${styleDir}`
    const { stderr } = await execAsync(command, { cwd, maxBuffer: 64 * 1024 * 1024 })
    if (stderr && !stderr.includes('warning') && stderr.trim() !== '') {
      // CLI sometimes writes progress to stderr — only flag real errors
      const looksLikeError = /error|fail|cannot|enoent/i.test(stderr)
      if (looksLikeError) {
        console.warn(`   ⚠️  CLI stderr for ${styleDir}:`, stderr.slice(0, 400))
      }
    }
  }
  finally {
    // 4. Remove the temp file regardless of success.
    await rimraf(tempRegistryPath)
  }

  return items.length
}

export async function buildStylesRegistry() {
  // eslint-disable-next-line no-console
  console.log('\n📤 Publishing per-style registries...')

  for (const style of STYLES) {
    const itemCount = await publishStyle(style.name)
    // eslint-disable-next-line no-console
    console.log(`   ✅ public/r/styles/${SOURCE_BASE}-${style.name}: ${itemCount} items`)
  }

  // eslint-disable-next-line no-console
  console.log('📤 Per-style registry publish complete.\n')
}
