// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const Index: Record<string, any> = {

"utils": {
  name: "utils",
  description: "",
  type: "registry:lib",
  registryDependencies: undefined,
  files: [{
    path: "registry/new-york-v4/lib/utils.ts",
    type: "registry:lib",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/lib/utils.ts").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"accordion": {
  name: "accordion",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/accordion/Accordion.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/accordion/AccordionContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/accordion/AccordionItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/accordion/AccordionTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/accordion/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/accordion/Accordion.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"alert": {
  name: "alert",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/alert/Alert.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert/AlertDescription.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert/AlertTitle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/alert/Alert.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"alert-dialog": {
  name: "alert-dialog",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils","button"],
  files: [{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialog.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialogAction.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialogCancel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialogContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialogDescription.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialogFooter.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialogHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialogTitle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/AlertDialogTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/alert-dialog/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/alert-dialog/AlertDialog.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"aspect-ratio": {
  name: "aspect-ratio",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/aspect-ratio/AspectRatio.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/aspect-ratio/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/aspect-ratio/AspectRatio.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"avatar": {
  name: "avatar",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/avatar/Avatar.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/avatar/AvatarFallback.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/avatar/AvatarImage.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/avatar/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/avatar/Avatar.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"badge": {
  name: "badge",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/badge/Badge.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/badge/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/badge/Badge.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"breadcrumb": {
  name: "breadcrumb",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/breadcrumb/Breadcrumb.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/breadcrumb/BreadcrumbEllipsis.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/breadcrumb/BreadcrumbItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/breadcrumb/BreadcrumbLink.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/breadcrumb/BreadcrumbList.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/breadcrumb/BreadcrumbPage.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/breadcrumb/BreadcrumbSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/breadcrumb/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/breadcrumb/Breadcrumb.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"button": {
  name: "button",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/button/Button.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/button/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/button/Button.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"calendar": {
  name: "calendar",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils","button"],
  files: [{
    path: "registry/new-york-v4/ui/calendar/Calendar.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarCell.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarCellTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarGrid.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarGridBody.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarGridHead.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarGridRow.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarHeadCell.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarHeading.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarNextButton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/CalendarPrevButton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/calendar/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/calendar/Calendar.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"card": {
  name: "card",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/card/Card.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/card/CardContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/card/CardDescription.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/card/CardFooter.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/card/CardHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/card/CardTitle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/card/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/card/Card.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"carousel": {
  name: "carousel",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils","button"],
  files: [{
    path: "registry/new-york-v4/ui/carousel/Carousel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/carousel/CarouselContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/carousel/CarouselItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/carousel/CarouselNext.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/carousel/CarouselPrevious.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/carousel/index.ts",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/carousel/interface.ts",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/carousel/useCarousel.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/carousel/Carousel.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"checkbox": {
  name: "checkbox",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/checkbox/Checkbox.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/checkbox/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/checkbox/Checkbox.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"collapsible": {
  name: "collapsible",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/collapsible/Collapsible.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/collapsible/CollapsibleContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/collapsible/CollapsibleTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/collapsible/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/collapsible/Collapsible.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"combobox": {
  name: "combobox",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/combobox/Combobox.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxAnchor.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxEmpty.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxInput.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxItemIndicator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxList.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/ComboboxViewport.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/combobox/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/combobox/Combobox.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"command": {
  name: "command",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils","dialog"],
  files: [{
    path: "registry/new-york-v4/ui/command/Command.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/CommandDialog.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/CommandEmpty.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/CommandGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/CommandInput.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/CommandItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/CommandList.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/CommandSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/CommandShortcut.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/command/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/command/Command.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"context-menu": {
  name: "context-menu",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/context-menu/ContextMenu.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuCheckboxItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuLabel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuPortal.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuRadioGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuRadioItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuShortcut.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuSub.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuSubContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuSubTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/ContextMenuTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/context-menu/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/context-menu/ContextMenu.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"dialog": {
  name: "dialog",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/dialog/Dialog.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogClose.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogDescription.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogFooter.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogOverlay.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogScrollContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogTitle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/DialogTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dialog/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/dialog/Dialog.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"drawer": {
  name: "drawer",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/drawer/Drawer.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/DrawerClose.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/DrawerContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/DrawerDescription.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/DrawerFooter.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/DrawerHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/DrawerOverlay.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/DrawerTitle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/DrawerTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/drawer/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/drawer/Drawer.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"dropdown-menu": {
  name: "dropdown-menu",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenu.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuCheckboxItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuLabel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuRadioGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuRadioItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuShortcut.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuSub.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuSubContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuSubTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/DropdownMenuTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/dropdown-menu/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/dropdown-menu/DropdownMenu.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"form": {
  name: "form",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils","label"],
  files: [{
    path: "registry/new-york-v4/ui/form/FormControl.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/form/FormDescription.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/form/FormItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/form/FormLabel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/form/FormMessage.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/form/index.ts",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/form/injectionKeys.ts",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/form/useFormField.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/form/FormControl.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"hover-card": {
  name: "hover-card",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/hover-card/HoverCard.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/hover-card/HoverCardContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/hover-card/HoverCardTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/hover-card/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/hover-card/HoverCard.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"input": {
  name: "input",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/input/Input.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/input/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/input/Input.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"label": {
  name: "label",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/label/Label.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/label/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/label/Label.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"menubar": {
  name: "menubar",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/menubar/Menubar.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarCheckboxItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarLabel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarMenu.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarRadioGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarRadioItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarShortcut.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarSub.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarSubContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarSubTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/MenubarTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/menubar/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/menubar/Menubar.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"navigation-menu": {
  name: "navigation-menu",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/navigation-menu/NavigationMenu.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/navigation-menu/NavigationMenuContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/navigation-menu/NavigationMenuIndicator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/navigation-menu/NavigationMenuItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/navigation-menu/NavigationMenuLink.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/navigation-menu/NavigationMenuList.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/navigation-menu/NavigationMenuTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/navigation-menu/NavigationMenuViewport.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/navigation-menu/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/navigation-menu/NavigationMenu.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"number-field": {
  name: "number-field",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/number-field/NumberField.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/number-field/NumberFieldContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/number-field/NumberFieldDecrement.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/number-field/NumberFieldIncrement.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/number-field/NumberFieldInput.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/number-field/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/number-field/NumberField.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"pagination": {
  name: "pagination",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils","button"],
  files: [{
    path: "registry/new-york-v4/ui/pagination/Pagination.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pagination/PaginationContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pagination/PaginationEllipsis.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pagination/PaginationFirst.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pagination/PaginationItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pagination/PaginationLast.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pagination/PaginationNext.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pagination/PaginationPrevious.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pagination/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/pagination/Pagination.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"pin-input": {
  name: "pin-input",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/pin-input/PinInput.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pin-input/PinInputGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pin-input/PinInputSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pin-input/PinInputSlot.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/pin-input/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/pin-input/PinInput.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"popover": {
  name: "popover",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/popover/Popover.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/popover/PopoverAnchor.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/popover/PopoverContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/popover/PopoverTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/popover/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/popover/Popover.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"progress": {
  name: "progress",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/progress/Progress.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/progress/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/progress/Progress.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"radio-group": {
  name: "radio-group",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/radio-group/RadioGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/radio-group/RadioGroupItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/radio-group/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/radio-group/RadioGroup.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"range-calendar": {
  name: "range-calendar",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils","button"],
  files: [{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendar.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarCell.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarCellTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarGrid.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarGridBody.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarGridHead.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarGridRow.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarHeadCell.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarHeading.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarNextButton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/RangeCalendarPrevButton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/range-calendar/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/range-calendar/RangeCalendar.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"resizable": {
  name: "resizable",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/resizable/ResizableHandle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/resizable/ResizablePanel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/resizable/ResizablePanelGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/resizable/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/resizable/ResizableHandle.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"scroll-area": {
  name: "scroll-area",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/scroll-area/ScrollArea.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/scroll-area/ScrollBar.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/scroll-area/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/scroll-area/ScrollArea.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"select": {
  name: "select",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/select/Select.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectItemText.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectLabel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectScrollDownButton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectScrollUpButton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/SelectValue.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/select/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/select/Select.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"separator": {
  name: "separator",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/separator/Separator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/separator/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/separator/Separator.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"sheet": {
  name: "sheet",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/sheet/Sheet.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/SheetClose.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/SheetContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/SheetDescription.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/SheetFooter.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/SheetHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/SheetOverlay.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/SheetTitle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/SheetTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sheet/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/sheet/Sheet.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"sidebar": {
  name: "sidebar",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils","sheet","input","tooltip","skeleton","separator","button"],
  files: [{
    path: "registry/new-york-v4/ui/sidebar/Sidebar.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarFooter.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarGroupAction.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarGroupContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarGroupLabel.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarInput.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarInset.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenu.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuAction.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuBadge.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuButton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuButtonChild.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuSkeleton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuSub.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuSubButton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarMenuSubItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarProvider.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarRail.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/SidebarTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/index.ts",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sidebar/utils.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/sidebar/Sidebar.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"skeleton": {
  name: "skeleton",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/skeleton/Skeleton.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/skeleton/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/skeleton/Skeleton.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"slider": {
  name: "slider",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/slider/Slider.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/slider/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/slider/Slider.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"sonner": {
  name: "sonner",
  description: "",
  type: "registry:ui",
  registryDependencies: [],
  files: [{
    path: "registry/new-york-v4/ui/sonner/Sonner.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/sonner/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/sonner/Sonner.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"stepper": {
  name: "stepper",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/stepper/Stepper.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/stepper/StepperDescription.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/stepper/StepperIndicator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/stepper/StepperItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/stepper/StepperSeparator.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/stepper/StepperTitle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/stepper/StepperTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/stepper/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/stepper/Stepper.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"switch": {
  name: "switch",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/switch/Switch.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/switch/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/switch/Switch.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"table": {
  name: "table",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/table/Table.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/TableBody.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/TableCaption.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/TableCell.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/TableEmpty.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/TableFooter.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/TableHead.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/TableHeader.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/TableRow.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/table/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/table/Table.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"tabs": {
  name: "tabs",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/tabs/Tabs.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tabs/TabsContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tabs/TabsList.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tabs/TabsTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tabs/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/tabs/Tabs.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"tags-input": {
  name: "tags-input",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/tags-input/TagsInput.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tags-input/TagsInputInput.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tags-input/TagsInputItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tags-input/TagsInputItemDelete.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tags-input/TagsInputItemText.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tags-input/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/tags-input/TagsInput.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"textarea": {
  name: "textarea",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/textarea/Textarea.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/textarea/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/textarea/Textarea.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"toggle": {
  name: "toggle",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/toggle/Toggle.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/toggle/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/toggle/Toggle.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"toggle-group": {
  name: "toggle-group",
  description: "",
  type: "registry:ui",
  registryDependencies: ["toggle","utils"],
  files: [{
    path: "registry/new-york-v4/ui/toggle-group/ToggleGroup.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/toggle-group/ToggleGroupItem.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/toggle-group/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/toggle-group/ToggleGroup.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
"tooltip": {
  name: "tooltip",
  description: "",
  type: "registry:ui",
  registryDependencies: ["utils"],
  files: [{
    path: "registry/new-york-v4/ui/tooltip/Tooltip.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tooltip/TooltipContent.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tooltip/TooltipProvider.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tooltip/TooltipTrigger.vue",
    type: "registry:ui",
    target: ""
  },{
    path: "registry/new-york-v4/ui/tooltip/index.ts",
    type: "registry:ui",
    target: ""
  }],
  component: () => import("@/registry/new-york-v4/ui/tooltip/Tooltip.vue").then((m) => m.default),
  source: "",
  category: "",
  subcategory: ""
},
}

