import type { Registry } from "shadcn-vue/schema"

export const blocks: Registry["items"] = [
  {
    name: "chatgpt",
    title: "ChatGPT",
    type: "registry:block",
    files: [
      {
        path: "blocks/chatgpt.vue",
        type: "registry:block",
      },
    ],
    registryDependencies: [
      "example",
      "alert",
      "alert-dialog",
      "badge",
      "button",
      "card",
      "dropdown-menu",
      "field",
      "input-group",
      "item",
      "kbd",
      "popover",
      "tooltip",
    ],
    dependencies: [],
    categories: [
      "blocks",
    ],
  },
  {
    name: "elevenlabs",
    title: "ElevenLabs",
    type: "registry:block",
    files: [
      {
        path: "blocks/elevenlabs.vue",
        type: "registry:block",
      },
    ],
    registryDependencies: [
      "example",
      "button",
      "card",
    ],
    dependencies: [],
    categories: [
      "blocks",
    ],
  },
  {
    name: "github",
    title: "GitHub",
    type: "registry:block",
    files: [
      {
        path: "blocks/github.vue",
        type: "registry:block",
      },
    ],
    registryDependencies: [
      "example",
      "avatar",
      "button",
      "card",
      "command",
      "drawer",
      "dropdown-menu",
      "empty",
      "field",
      "input-group",
      "item",
      "kbd",
      "popover",
      "separator",
      "spinner",
      "tabs",
      "tooltip",
    ],
    dependencies: [],
    categories: [
      "blocks",
    ],
  },
  {
    name: "preview",
    title: "Home",
    type: "registry:block",
    files: [
      {
        path: "blocks/preview.vue",
        type: "registry:block",
      },
    ],
    registryDependencies: [
      "example",
      "alert-dialog",
      "avatar",
      "badge",
      "button",
      "button-group",
      "card",
      "checkbox",
      "dropdown-menu",
      "empty",
      "field",
      "input",
      "input-group",
      "item",
      "radio-group",
      "select",
      "separator",
      "sheet",
      "slider",
      "switch",
      "textarea",
      "tooltip",
    ],
    dependencies: [],
    categories: [
      "blocks",
    ],
  },
  {
    name: "vercel",
    title: "Vercel",
    type: "registry:block",
    files: [
      {
        path: "blocks/vercel.vue",
        type: "registry:block",
      },
    ],
    registryDependencies: [
      "example",
      "alert",
      "badge",
      "button",
      "calendar",
      "card",
      "dialog",
      "dropdown-menu",
      "empty",
      "field",
      "input-group",
      "item",
      "native-select",
      "popover",
      "textarea",
    ],
    dependencies: [
      "reka-ui",
    ],
    categories: [
      "blocks",
    ],
  },
]
