/* eslint-disable ts/ban-ts-comment */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Icons = {
  "AlertCircle": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.AlertCircle
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.ExclamationTriangleIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconExclamationCircle
  })),
},  "ArrowLeft": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.ArrowLeft
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.ArrowLeftIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconArrowLeft
  })),
},  "ArrowRight": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.ArrowRight
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.ArrowRightIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconArrowRight
  })),
},  "ArrowUpDown": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.ArrowUpDown
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.CaretSortIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconArrowsSort
  })),
},  "BellRing": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.BellRing
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.BellIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconBellRinging
  })),
},  "Bold": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Bold
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.FontBoldIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconBold
  })),
},  "Calculator": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Calculator
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.ComponentPlaceholderIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconCalculator
  })),
},  "Calendar": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Calendar
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.CalendarIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconCalendar
  })),
},  "Check": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Check
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.CheckIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconCheck
  })),
},  "ChevronDown": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.ChevronDown
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.ChevronDownIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconChevronDown
  })),
},  "ChevronLeft": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.ChevronLeft
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.ChevronLeftIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconChevronLeft
  })),
},  "ChevronRight": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.ChevronRight
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.ChevronRightIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconChevronRight
  })),
},  "ChevronUp": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.ChevronUp
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.ChevronUpIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconChevronUp
  })),
},  "ChevronsUpDown": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.ChevronsUpDown
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.CaretSortIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconSelector
  })),
},  "Circle": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Circle
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.DotFilledIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconCircle
  })),
},  "Copy": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Copy
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.CopyIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconCopy
  })),
},  "CreditCard": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.CreditCard
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.ComponentPlaceholderIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconCreditCard
  })),
},  "GripVertical": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.GripVertical
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.DragHandleDots2Icon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconGripVertical
  })),
},  "Italic": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Italic
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.FontItalicIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconItalic
  })),
},  "Loader2": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Loader2
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.ReloadIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconLoader2
  })),
},  "Mail": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Mail
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.EnvelopeClosedIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconMail
  })),
},  "MailOpen": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.MailOpen
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.EnvelopeOpenIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconMailOpened
  })),
},  "Minus": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Minus
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.MinusIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconMinus
  })),
},  "Moon": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Moon
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.MoonIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconMoon
  })),
},  "MoreHorizontal": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.MoreHorizontal
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.DotsHorizontalIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconDots
  })),
},  "PanelLeft": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.PanelLeft
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.ViewVerticalIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconLayoutSidebar
  })),
},  "Plus": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Plus
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.PlusIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconPlus
  })),
},  "Search": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Search
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.MagnifyingGlassIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconSearch
  })),
},  "Send": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Send
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.PaperPlaneIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconSend
  })),
},  "Settings": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Settings
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.GearIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconSettings
  })),
},  "Slash": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Slash
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.SlashIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconSlash
  })),
},  "Smile": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Smile
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.FaceIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconMoodSmile
  })),
},  "Sun": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Sun
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.SunIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconSun
  })),
},  "Terminal": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Terminal
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.RocketIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconTerminal
  })),
},  "Underline": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.Underline
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.UnderlineIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconUnderline
  })),
},  "User": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.User
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.PersonIcon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconUser
  })),
},  "X": {
  lucide:  () => import("lucide-vue-next").then(mod => ({
    default: mod.X
  })),
  radix:  () => import("@radix-icons/vue").then(mod => ({
    default: mod.Cross2Icon
  })),
  tabler:  () => import("@tabler/icons-vue").then(mod => ({
    default: mod.IconX
  })),
},
}

