name: Preview Module release

permissions:
  pull-requests: write

on:
  pull_request:
  push:
    types: [opened, synchronize, labeled]
    paths:
      - packages/module/**
    path-ignore:
      - 'test/**'
      - '*.md'
    tags-ignore:
      - '*'

jobs:
  preview:
    if: >
      github.repository == 'unovue/shadcn-vue' &&
      (github.event_name == 'push' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'trigger: module preview')))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Install dependencies
        run: pnpm install

      - name: Build
        working-directory: ./packages/module
        run: pnpm build

      - run: pnpm dlx pkg-pr-new publish --compact --no-template --pnpm ./packages/module
